import { logo } from '@assets';

export const sidebarConfig = {
    title: 'MET',
    logo: logo,
    studentNavLinks: [
        { name: 'Overview', href: '/student' },
        { name: 'Assignments', href: '/student/assignments' },
        { name: 'Internal Results', href: '/student/internal-results' },
        { name: 'Semester Results', href: '/student/semester-results' },
        { name: 'Download Notes', href: '/student/download-notes' },
        { name: 'Pay Dues', href: '/student/dues' },
        { name: 'Dues & Approvals', href: '/student/approvals' },
        { name: 'Time Table', href: '/student/timetable' },
        { name: 'Circular', href: '/student/circulars' },
        { name: 'Events', href: '/student/events' },
    ],
    facultyNavLinks: [
        { name: 'Overview', href: '/faculty' },
        { name: 'Students', href: '/faculty/students' },
        { name: 'Assignments', href: '/faculty/assignments' },
        { name: 'Internal Results', href: '/faculty/internal-results' },
        { name: 'Semester Results', href: '/faculty/semester-results' },
        { name: 'Download Notes', href: '/faculty/download-notes' },
        { name: 'Dues', href: '/faculty/dues' },
        { name: 'Dues & Approvals', href: '/faculty/approvals' },
        { name: 'Timetable', href: '/faculty/timetable' },
        { name: 'Circular', href: '/faculty/circulars' },
        { name: 'Events', href: '/faculty/events' },
    ],
    adminNavLinks: [
        { name: 'Overview', href: '/admin' },
        { name: 'Faculties', href: '/admin/faculties' },
        { name: 'Students', href: '/admin/students' },
        { name: 'Assignments', href: '/admin/assignments' },
        { name: 'Internal Results', href: '/admin/internal-results' },
        { name: 'Semester Results', href: '/admin/semester-results' },
        { name: 'Download Notes', href: '/admin/download-notes' },
        { name: 'Dues', href: '/admin/dues' },
        { name: 'Dues & Approvals', href: '/admin/approvals' },
        { name: 'Timetable', href: '/admin/timetable' },
        { name: 'Circular', href: '/admin/circulars' },
        { name: 'Events', href: '/admin/events' },
    ],
};
