export const STUDENT_TABLE_INPUT_FIELDS = [
    {
        label: 'Profile Image',
        type: 'file',
        placeholder: 'Select profile',
        name: 'profileImage',
        fileType: 'image/png, image/jpeg',
    },
    {
        label: 'Name',
        type: 'text',
        placeholder: 'Enter name',
        name: 'name',
    },
    {
        label: 'Register Number',
        type: 'number',
        placeholder: 'Enter register number',
        name: 'registerNo',
    },
    {
        label: 'CGPA',
        type: 'number',
        placeholder: '0',
        name: 'cgpa',
        float: true,
    },
    {
        label: 'Attendance (%)',
        type: 'number',
        placeholder: '0',
        name: 'attendance',
    },
    {
        label: 'Dues',
        type: 'number',
        placeholder: '0',
        name: 'dues',
    },
    {
        label: 'Date of Birth',
        type: 'date',
        placeholder: 'Select date of birth',
        name: 'dob',
    },
    {
        label: 'Gender',
        type: 'select',
        placeholder: 'Select gender',
        name: 'gender',
        options: [
            { label: 'Male', value: 'Male' },
            { label: 'Female', value: 'Female' },
        ],
    },
    {
        label: 'Department',
        type: 'select',
        placeholder: 'CSE',
        name: 'department',
        options: [{ label: 'CSE', value: 'CSE' }],
    },
    {
        label: 'Year',
        type: 'select',
        name: 'year',
        valueAsNumber: true,
        options: [
            { label: '1', value: 1 },
            { label: '2', value: 2 },
            { label: '3', value: 3 },
            { label: '4', value: 4 },
        ],
    },
    {
        label: 'Regulation',
        type: 'select',
        placeholder: 'regulation',
        name: 'regulation',
        options: [
            { label: '2021', value: 'R2021' },
            { label: '2025', value: 'R2025' },
        ],
    },
    {
        label: 'Semester',
        type: 'select',
        placeholder: 'Enter semester',
        valueAsNumber: true,
        name: 'semester',
        options: [
            { label: '1', value: 1 },
            { label: '2', value: 2 },
            { label: '3', value: 3 },
            { label: '4', value: 4 },
            { label: '5', value: 5 },
            { label: '6', value: 6 },
            { label: '7', value: 7 },
            { label: '8', value: 8 },
        ],
    },
    {
        label: 'Batch',
        type: 'select',
        placeholder: 'Enter batch',
        name: 'batch',
        options: [
            { label: '2021-2025', value: '2021-2025' },
            { label: '2025-2029', value: '2025-2029' },
        ],
    },
    {
        label: 'Arrears',
        type: 'number',
        placeholder: '0',
        name: 'arrears',
    },
    {
        label: 'Degree',
        type: 'select',
        placeholder: 'Degree',
        name: 'degree',
        options: [{ label: 'B.E', value: 'B.E' }],
    },
    {
        label: 'Email',
        type: 'text',
        placeholder: 'Enter email',
        name: 'email',
    },
    {
        label: 'Mobile',
        type: 'number',
        placeholder: 'Enter mobile number',
        name: 'mobile',
    },
    {
        label: 'Accommodation',
        type: 'select',
        placeholder: 'Select accommodation',
        name: 'accommodation',
        options: [
            { label: 'Day Scholar', value: 'Day Scholar' },
            { label: 'Hosteller', value: 'Hosteller' },
        ],
    },
    {
        label: 'Password',
        type: 'password',
        placeholder: 'Enter password',
        name: 'password',
    },
];
