export const STUDENT_TABLE_INPUT_FIELDS = [
    {
        label: 'Profile Image',
        type: 'file',
        placeholder: 'Select profile',
        name: 'profileImage',
        valueAsNumber: false,
    },
    {
        label: 'Name',
        type: 'text',
        placeholder: 'Enter name',
        name: 'name',
        valueAsNumber: false,
    },
    {
        label: 'Register Number',
        type: 'number',
        placeholder: 'Enter register number',
        name: 'registerNo',
        valueAsNumber: true,
    },
    {
        label: 'CGPA',
        type: 'number',
        placeholder: 'Enter CGPA',
        name: 'cgpa',
        valueAsNumber: true,
        float: true,
    },
    {
        label: 'Attendance (%)',
        type: 'number',
        placeholder: 'Enter attendance',
        name: 'attendance',
        valueAsNumber: true,
    },
    {
        label: 'Dues',
        type: 'number',
        placeholder: 'Enter dues amount',
        name: 'dues',
        valueAsNumber: true,
    },
    {
        label: 'Date of Birth',
        type: 'date',
        placeholder: 'Select date of birth',
        name: 'dob',
        valueAsNumber: false,
    },
    {
        label: 'Gender',
        type: 'select',
        placeholder: 'Select gender',
        name: 'gender',
        valueAsNumber: false,
        options: [
            { label: 'Male', value: 'Male' },
            { label: 'Female', value: 'Female' },
        ],
    },
    {
        label: 'Department',
        type: 'text',
        placeholder: 'Enter department',
        name: 'department',
        valueAsNumber: false,
    },
    {
        label: 'Year',
        type: 'number',
        placeholder: 'Enter year',
        name: 'year',
        valueAsNumber: true,
    },
    {
        label: 'Regulation',
        type: 'text',
        placeholder: 'Enter regulation',
        name: 'regulation',
        valueAsNumber: false,
    },
    {
        label: 'Semester',
        type: 'number',
        placeholder: 'Enter semester',
        name: 'semester',
        valueAsNumber: true,
    },
    {
        label: 'Batch',
        type: 'text',
        placeholder: 'Enter batch',
        name: 'batch',
        valueAsNumber: false,
    },
    {
        label: 'Arrears',
        type: 'number',
        placeholder: 'Enter arrears count',
        name: 'arrears',
        valueAsNumber: true,
    },
    {
        label: 'Degree',
        type: 'text',
        placeholder: 'Enter degree',
        name: 'degree',
        valueAsNumber: false,
    },
    {
        label: 'Email',
        type: 'text',
        placeholder: 'Enter email',
        name: 'email',
        valueAsNumber: false,
    },
    {
        label: 'Mobile',
        type: 'number',
        placeholder: 'Enter mobile number',
        name: 'mobile',
        valueAsNumber: true,
    },
    {
        label: 'Accommodation',
        type: 'select',
        placeholder: 'Select accommodation',
        name: 'accomodation',
        valueAsNumber: false,
        options: [
            { label: 'Day Scholar', value: 'Day Scholar' },
            { label: 'Hosteller', value: 'Hosteller' },
        ],
    },
    {
        label: 'Password',
        type: 'password',
        placeholder: 'Enter password',
        name: 'password',
        valueAsNumber: false,
    },
];
