export * from './regulationInfo.types';
export * from './student.types';
export * from './assignment.types';
export * from './internalResult.types';
export * from './semesterResult.types';
export * from './userRoles.types';
export * from './dues.types';
export * from './queryParams';
export * from './payment.types';
